library(CoordinateCleaner)
library(cowplot)
library(data.table)
library(DescTools)
library(fasterize)
library(fitdistrplus)
library(gdalUtils)
# also need to have a working GDAL on your system
# can download at trac.osgeo.org/osgeo4w/ 
library(ggpmisc)
library(ggrepel)
library(ggspatial)
library(gitcreds)
library(gridExtra)
library(here)
library(lhs)
library(magrittr)
library(patchwork)
library(piggyback)
library(raster)
library(rasterVis)
library(RColorBrewer)
library(rentrez)
library(rgbif)
library(rgdal)
# disable creation of xml files
rgdal::setCPLConfigOption("GDAL_PAM_ENABLED", "FALSE")
library(rnaturalearth)
library(rnaturalearthdata)
library(rredlist)
library(rworldmap)
library(scales)
library(sensitivity)
library(sp)
library(sf)
#devtools::install_github("ropensci/taxadb")
library(taxadb)
library(taxize)
library(tidyverse)
library(usethis)
library(viridis)
library(viridisLite)
library(yarrr)