library(tidyverse)
library(magrittr)
library(raster)
library(rasterVis)
library(fasterize)
library(viridis)
library(viridisLite)
library(sp)
library(sf)
#devtools::install_github("ropensci/taxadb")
library(taxadb)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgdal)
# disable creation of xml files
rgdal::setCPLConfigOption("GDAL_PAM_ENABLED", "FALSE")
library(gdalUtils)
# also have to have a working GDAL on your system
# can download at trac.osgeo.org/osgeo4w/ 
library(rgbif)
library(data.table)
library(taxize)
library(yarrr)
library(CoordinateCleaner)
library(gridExtra)
library(ggrepel)
library(ggpmisc)
library(fitdistrplus)
library(scales)
library(lhs)
library(sensitivity)